# GitHub Sponsors (can list up to 4 usernames/organizations)
github: [hellfurian1228]
# Up to 4 custom URLs (great for PayPal, Stripe links, or your own website)
custom: https://ko-fi.com/M4C4261YJA, https://www.paypal.com/donate/?hosted_button_id=P3P43EXYJWRLC
